Update `pandas` minimum version to `2.1.0` in requirements.txt
Lower pandas version may throw an error `AttributeError: 'DataFrame' object has no attribute 'map'` (rising from `__replace_values_df` function in the file `preprocess.py`). 

This was changed in pandas version `2.1.0` where `map` function was provided on dataframe and `applymap` was  deprecated.